### ISSUE TITLE
Updating the current dev build for Windows 11

### ISSUE THREAD

**Issue by cappuchi** [Goldfish64/NinjaCatDiscordBot#11]
So the new build just got released in Wednesday called 22000.120 and it is available for beta and dev insiders. When I check for the current insider build, then it shows that it is 22000.120, however when I check for the current dev build, it shows that the current build is 22000.100:
![image](https://user-images.githubusercontent.com/71344841/128456159-b7fcf720-d47d-4fbf-a924-4dfadb7bc50a.png)
Screenshot taken from Microsoft Community discord server.

**Comment by dongle-the-gadget** [comment]
The bot checks for Windows Insiders Blog Post description. It will look for these keywords to determine the correct channel:
```
server
dev cha
beta and (the) release preview cha
beta cha
release preview cha
```
In the 22000.120 build post, they said: "Dev and Beta Channel", it doesn't find references of "dev cha", so it will think this build is not in the Dev channel, hence why it's malfunctioning.

**Comment by dongle-the-gadget** [comment]
I guess that usually Dev Insiders would be moved to a newer build before an existing one would be flighted to Beta.

**Comment by Goldfish64** [comment]
Fixed in https://github.com/Goldfish64/NinjaCatDiscordBot/commit/c7101b7849ec6f4dc0de5718f23e2100dac4ba65.
