### ISSUE TITLE
Use an unambiguous date format

### ISSUE THREAD

**Issue by ThatRandomToast** [Goldfish64/NinjaCatDiscordBot#6]
The dates that are being shown are in MM/DD/YYYY format which is primarily used in the United States.

Please switch dates to the YYYY-MM-DD (ISO:8601) format to remove ambiguity. Depending on where you are in the world, 11/12/2020 could be 11 December 2020 or November 12, 2020, but 2020-11-12 is only 12 November 2020.

**Comment by Goldfish64** [comment]
Fixed in 970bc16.
