### ISSUE TITLE
Change bot's new insider version announcement / bot commands response.

### ISSUE THREAD

**Issue by ParkoutV** [Goldfish64/NinjaCatDiscordBot#8]
This is my personal suggestion about @Ninja Cat#0262 bot's new insider version announcement / bot commands response. Since you might not see this in moderator mail in ms discord server so I send issues page on here.
I think it would be better to change some sentence -  "Windows 10 Insider" to "Windows Insider"

ex) 
> The latest Windows 10 Beta Channel build is 19042.1081. -> The latest Windows insider Beta Channel build is 19042.1081.
> Windows 10 Insider Preview Build **22000** has just been released to the Dev Channel! Yes! :smiley_cat: :tools: -> Windows Insider Preview Build **22000** has just been released to the Dev Channel! Yes! :smiley_cat: :tools:

I think that would be better then just specifying what windows version it is (like win10 or 11) because it is hard to recognize for bot what windows version they're taking from now on
(especially when they develop both Win10 and Win11 across several channels)

**Comment by Erisa** [comment]
For some channels though (Dev from now onwards, and Beta soon) it's pretty much confirmed all they're going to be flighting is Windows 11 for the forseeable future, so you might as well just make it always show that for those channels after those times.

Release Preview is the only channel I know of that will stick with Windows 10 for now.

**Comment by Goldfish64** [comment]
Fixed in https://github.com/Goldfish64/NinjaCatDiscordBot/commit/cf5920e842a011f759c86c8af7367135cec3c3e2.
